Itaseki/itaseki-front

src/Pages/Board/Community.js
src/Pages/Board/CommunityDetail.js

새 잡담 게시글 등록 기능 구현 완료

---

src/Components/YoutubeAPI.js
src/Pages/Video/AddNewVideo.js

- 유튜브 영상 데이터(영상 제목, 채널 이름, 썸네일, 재생시간) 가져오기   #13
- 새로운 영상 등록 #13

[FEAT] 유튜브API로 영상 데이터 가져오기 & 영상 등록 기능

---

src/App.js
src/Pages/Run/AddReserv.js
src/preURL/preURL.js

- 예약할 영상 제목 검색/연관 검색어 노출 추가
**AddReserv.js**
- Reservation.js 분리
- 예약할 영상 제목 검색
- 연관 검색어 노출
- 선택된 제목에 포함된 정보 정리

[FEAT/DESIGN] 예약할 영상 제목 검색/연관 검색어 노출 추가

---

src/Components/Main/OneVideo.js
src/Components/Main/Oneply.js
src/Pages/Main.js

[FEAT] 메인 페이지 하단 Wrapper(미완)

---

src/Components/TimeStamp.js

[FEAT] 시간 표현 수정

---

src/Components/Token.js
src/Pages/Playlist/SubscribedPly.js

[FEAT] 구독 플레이리스트 조회, 토큰값 리턴 컴포넌트 생성

---

src/Pages/Run/ReservationList.js
src/Pages/Run/TimeTable.js
src/Pages/Run/TodayPopVids.js

인기 예약 조회 추가(백엔드 테스트 미완료)
**TimeTable.js**
- 타임테이블 블록 추가
**TodayPopVids.js**
- 인기 예약 조회 추가
* 현재 예약 데이터가 없어서 백엔드 테스트 미완료

 [FEAT/DESIGN] 인기 예약 조회(백엔드 테스트 미완료)/타임테이블 블록 추가

---

src/Components/Header.js

[FEAT] 로그아웃

---

src/Pages/Run/AddReserv.js
src/Pages/Run/Detail.js
src/Pages/Run/Reservation.js
src/Pages/Run/TimeTable.js
src/Pages/Run/TodayPopVids.js

타임테이블 수정
**TodayPopVids**
- 위치 수정
- 예약하기 클릭시 예약 수 변경 추가
**Detail.js**
- 예약 목록(확정/대기) 클릭 시 나타나는 모달 추가
**Timetable.js**
- 블록 클릭 시 색 변경
- 시간별 타임테이블 조회 추가

[FEAT/DESIGN] 타임테이블 수정

---

src/Components/Header.js

- 회원 탈퇴하기
- 탈퇴 시 유의사항 공지
- 유의사항 미동의 시 - 탈퇴 취소
- 유의사항 동의 시 - 탈퇴 완료
- 백엔드 기능X

[FEAT] 탈퇴하기(백엔드X)

---

src/Pages/Board/GIFBoard.js
src/Pages/Board/GIFBoardDetail.js
src/Pages/Main.js
src/Pages/Run/AddReserv.js
src/Pages/Run/Detail.js
src/Pages/Run/ReservationList.js
src/Pages/Run/TimeTable.js
src/Pages/Run/TodayPopVids.js
src/Style/AddReserv.js
src/Style/Detail.js
src/Style/TimeTable.js
src/Style/TodayPopVids.js
src/TestData/BoardTestData.js
src/TestData/MainTest.js
src/TestData/ReservTest.js

색 고정 / 시간 값 수정
- 테스트(더미) 데이터 분리
**AddReserv**
- 날짜 색 고정
**TimeTable**
- 현재 일자 기준 날짜 변경
- timeZone 값 더하기 구현(날짜가 넘어갔을 경우 수정 필요)
- runTime에 따라 제목 길이 변경

 [Refactor/Fix/Feat] 색 고정 / 시간 값 수정

---

.idea/workspace.xml
src/Components/Header.js
src/Components/Modal.js
src/Pages/Board/Community.js
src/Style/Community.js

[FEAT] 새 잡담글 작성 시 이미지 첨부 미리보기 추가

---

src/Pages/Playlist/AllPlaylist.js
src/Pages/Video/AllVideo.js

- 영상 & 플리게시판의 전체 조회 get요청 주소에서 검색 제외

[REFACTOR] 영상&플리게시판 전체조회 요청 주소 수정

---

src/Components/Chat/ChatContainer.js
src/Components/Comment/CommentList.js
src/Components/Comment/SingleComment.js
src/Components/Header.js
src/Components/Playlist/AddVideoToPlaylistModal.js
src/Components/Playlist/NewPlaylistModal.js
src/Components/Playlist/SavePlyModal.js
src/Components/Token.js
src/Components/Video/OneVideo.js
src/Pages/Playlist/PlaylistDetail.js
src/Pages/Playlist/SubscribedPly.js
src/Pages/Run/Running.js
src/Pages/Video/AddNewVideo.js
src/Pages/Video/AllVideo.js
src/Pages/Video/VideoDetail.js

- 로그인 토큰 필요한 요청 url에 토큰 연결
- 상세 게시글 조회 시 토큰 없이도 조회 가능하도록 수정해야 함(로그인 안 한 외부 사용자가 접속 시)

[FIX] 로그인 토큰 연결

---

src/Components/Chat/ChatContainer.js
src/Components/Comment/CommentList.js
src/Components/Comment/SingleComment.js
src/Components/Header.js
src/Components/Playlist/AddVideoToPlaylistModal.js
src/Components/Playlist/NewPlaylistModal.js
src/Components/Playlist/SavePlyModal.js
src/Components/TimeStamp.js
src/Components/Video/OneVideo.js
src/Pages/Playlist/PlaylistDetail.js
src/Pages/Playlist/SubscribedPly.js
src/Pages/Run/Running.js
src/Pages/Video/AddNewVideo.js
src/Pages/Video/AllVideo.js
src/Pages/Video/VideoDetail.js

[DESIGN] 시간 표현 수정

---

src/Pages/Playlist/PlaylistDetail.js

- 플레이리스트 상세게시물 조회 불가능 오류 수정
- 클릭한 영상 id와 플리모달 id가 일치할 때 모달이 뜨도록 구현

[FIX] 플레이리스트 상세게시물 조회 불가능 오류 수정

---

src/Components/Comment/SingleComment.js
src/Pages/Playlist/PlaylistDetail.js
src/Pages/Video/AddNewVideo.js
src/Pages/Video/VideoDetail.js

- 신고 버튼 클릭 시 '신고 하시겠습니까?'라는 alert창을 먼저 띄워 사용자에게 번복 가능성 제공

[REFACTOR] 신고 기능 보완

---

src/Pages/Run/AddReserv.js
src/Pages/Run/TimeTable.js

기능 수정
- 타임테이블 색 수정
- 영상 적용 여부 팝업 수정
**TimeTable.js**
- 블럭 색 변경 기능 수정
**AddResrv.js**
- 영상 적용 여부 rItem으로 변경

[Fix] 타임테이블 색 수정, 영상 적용 여부 팝업 수정

---

src/Pages/Run/TimeTable.js
src/Style/TimeTable.js

디자인 변경
**TimeTable**
- 타임테이블 리뉴얼된 디자인으로 변경

[Design] 타임테이블 디자인 변경

---

src/Components/Header.js

[FIX] 로그아웃 수정

---

src/Components/Header.js
src/Pages/Start/LoginRedirect.js
yarn.lock

- 로그인 후 useNavigate를 사용하여 화면 리로드 없이 메인으로 이동하였더니 앱의 가장 상위에 있는 Store의 유저 정보 불러오기 요청이 실행되지 않음 => window.location.replace()를 사용하여 화면이 리로드됨으로써 유저 정보 요청이 실행될 수 있도록 함 (해결O)

[FIX] 로그인 시 프로필 이미지 바로 안 뜨는 오류 수정

---

src/Components/Header.js
src/Style/Color.js

- 상단 헤더 프로필 조회 모달창 디자인 및 내용 수정
- hover시 배경색 수정해야할 수도 있음

[DESIGN] 상단 헤더 프로필 조회 모달창 디자인 수정

---

src/Pages/Main.js
src/Style/Main.js
yarn.lock

디자인 변경
**Main.js**
- 인기 영상 플레이리스트 추가(기능, 디자인)
- 인기 영상 슬라이더 (미완성)

[Feat/Design]

---

src/Pages/Search/Search.js
src/Style/Search.js

검색 결과 수정
**Search**
- 검색하지 않을 경우 pagination 숨김
- OneVideo, OnePly 컨테이너 추가

[Feat/Fix] 검색 결과 수정

---

src/Components/Header.js

[Design] 카테고리 색 추가
